// simple_dither_generator for the Hothouse DIY DSP platform.
//
// Firmware entry point: composes the platform-agnostic EffectProcessor with the
// Hothouse hardware adapter. Generated by HeadroomLab.
#include "effect_processor.h"
#include "hothouse_adapter.h"
#include <memory>

using clevelandmusicco::Hothouse;
using daisy::SaiHandle;

Hothouse hw;
std::unique_ptr<EffectProcessor> processor;
std::unique_ptr<HothouseAdapter> adapter;

int main() {
    hw.Init();
    hw.SetAudioBlockSize(48);
    hw.SetAudioSampleRate(SaiHandle::Config::SampleRate::SAI_48KHZ);

    processor = std::make_unique<EffectProcessor>(hw.AudioSampleRate());
    adapter = std::make_unique<HothouseAdapter>(hw, *processor);

    hw.StartAdc();
    hw.StartAudio(HothouseAdapter::AudioCallback);

    while (true) {
        // Control-rate updates (knobs/switches -> DSP atomics).
        adapter->updateControls();
        hw.DelayMs(10); // avoid busy-waiting
        // FOOTSWITCH_1 held 2s -> DFU/bootloader.
        hw.CheckResetToBootloader();
    }

    return 0;
}
